# Generated by Django 5.2.4 on 2025-07-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('codigo_sku', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('unidade_medida', models.CharField(default='unidade', max_length=50, verbose_name='Unidade de Medida')),
                ('localizacao_estoque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização no Estoque')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor Principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Produto Ativo')),
                ('limite_estoque_minimo', models.IntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('limite_estoque_maximo', models.IntegerField(default=100, verbose_name='Estoque Máximo')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
