# Generated by Django 5.2.4 on 2025-07-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_cadastrado_por_produto_cadastrado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Imagem do Produto'),
        ),
    ]
