# Generated by Django 5.2.4 on 2025-07-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='Tipo de Movimentação'),
        ),
    ]
